/* 목업 데이터.
   실제 프로젝트에서는 백엔드 API(/api/notices)로 대체됩니다.
   지금은 브라우저 메모리에만 있으므로, 새로고침하면 초기 상태로 돌아갑니다. */

window.CATEGORIES = ["학사", "행사", "장학", "채용", "일반"];

window.NOTICES = [
  { id: 30, category: "장학", title: "2학기 국가장학금 2차 신청 안내", author: "김민준", department: "학생지원팀", createdAt: "2026-08-04", dueDate: "2026-08-17", views: 412, isPinned: true,
    content: "2026학년도 2학기 국가장학금 2차 신청이 시작되었습니다.\n\n■ 신청 기간\n2026년 8월 4일(화) 09:00 ~ 8월 17일(월) 18:00\n\n■ 신청 방법\n한국장학재단 홈페이지 또는 모바일 앱에서 신청\n\n■ 유의사항\n- 1차에서 미신청한 신입생, 편입생, 재입학생이 대상입니다.\n- 가구원 동의와 서류 제출까지 완료해야 신청이 마감됩니다.\n- 기한을 넘기면 2학기 국가장학금을 받을 수 없습니다.\n\n문의: 학생지원팀 032-000-0000" },
  { id: 29, category: "학사", title: "수강 정정 기간 및 유의사항 안내", author: "박서연", department: "학사지원팀", createdAt: "2026-08-10", dueDate: "2026-08-21", views: 188, isPinned: false,
    content: "2학기 수강 정정 기간을 안내드립니다.\n\n■ 기간: 2026년 8월 19일(수) ~ 8월 21일(금)\n■ 방법: 학사정보시스템 > 수강신청 > 정정\n\n정정 기간 이후에는 어떠한 사유로도 변경이 불가하니 시간표를 미리 확인해 주세요." },
  { id: 28, category: "행사", title: "한빛 축제 부스 운영팀 모집", author: "이도현", department: "총학생회", createdAt: "2026-08-09", dueDate: "2026-08-20", views: 95, isPinned: false,
    content: "제32회 한빛 축제에서 함께할 부스 운영팀을 모집합니다.\n\n■ 모집 인원: 20명\n■ 활동 기간: 9월 22일 ~ 9월 24일\n■ 지원 방법: 총학생회 인스타그램 링크로 신청\n\n봉사시간이 인정됩니다." },
  { id: 27, category: "채용", title: "2026 하반기 공채 대비 특강 신청", author: "정하윤", department: "취업지원센터", createdAt: "2026-08-08", dueDate: "2026-08-18", views: 231, isPinned: false,
    content: "하반기 공채를 준비하는 재학생을 위한 특강을 엽니다.\n\n■ 일정: 8월 25일 ~ 8월 27일 (3일)\n■ 장소: 본관 3층 대강의실\n■ 내용: 자기소개서 작성, 인적성 대비, 모의 면접\n\n선착순 60명이며 전 학년 신청 가능합니다." },
  { id: 26, category: "학사", title: "하계 계절학기 성적 정정 기간", author: "박서연", department: "학사지원팀", createdAt: "2026-08-07", dueDate: "2026-08-14", views: 176, isPinned: false,
    content: "하계 계절학기 성적 정정 기간을 안내합니다.\n\n■ 기간: 8월 12일(수) ~ 8월 14일(금)\n■ 방법: 담당 교수님께 직접 문의\n\n정정 기간 이후 성적은 확정되며 변경되지 않습니다." },
  { id: 25, category: "일반", title: "교내 주차장 공사에 따른 통행 안내", author: "최우진", department: "시설관리팀", createdAt: "2026-08-06", dueDate: null, views: 64, isPinned: false,
    content: "제2주차장 포장 공사로 인해 아래와 같이 통행이 제한됩니다.\n\n■ 기간: 8월 10일 ~ 8월 28일\n■ 제한 구역: 제2주차장 전체\n■ 대체 주차: 제1주차장, 체육관 앞 임시 주차 구역\n\n이용에 불편을 드려 죄송합니다." },
  { id: 24, category: "장학", title: "근로장학생 2차 모집 공고", author: "김민준", department: "학생지원팀", createdAt: "2026-08-05", dueDate: "2026-08-15", views: 308, isPinned: false,
    content: "2학기 교내 근로장학생을 모집합니다.\n\n■ 모집 인원: 45명\n■ 근로 시간: 주 10시간 이내\n■ 지급액: 시간당 11,000원\n■ 신청: 학사정보시스템 > 장학 > 근로장학 신청\n\n소득분위 8분위 이하 우선 선발합니다." },
  { id: 23, category: "장학", title: "교내 성적우수 장학 신청 안내", author: "김민준", department: "학생지원팀", createdAt: "2026-07-28", dueDate: "2026-08-16", views: 264, isPinned: false,
    content: "직전 학기 성적 우수자를 대상으로 교내 장학금을 지급합니다.\n\n■ 대상: 직전 학기 평점 4.0 이상, 15학점 이상 이수자\n■ 지급액: 등록금의 30~100%\n■ 신청 기간: 8월 3일 ~ 8월 16일\n\n별도 신청 없이 자동 선발되는 경우도 있습니다." },
  { id: 22, category: "행사", title: "제32회 한빛 체육대회 참가 신청", author: "이도현", department: "총학생회", createdAt: "2026-08-04", dueDate: "2026-09-05", views: 142, isPinned: false,
    content: "학과 대항 체육대회 참가 신청을 받습니다.\n\n■ 일정: 9월 12일(금)\n■ 종목: 축구, 농구, 피구, 줄다리기, 이어달리기\n■ 신청: 학과 학생회를 통해 일괄 접수" },
  { id: 21, category: "채용", title: "LINC 산학협력 인턴십 모집", author: "한지우", department: "산학협력단", createdAt: "2026-08-03", dueDate: "2026-08-19", views: 197, isPinned: false,
    content: "산학협력 가족회사와 함께하는 현장 실습 인턴십입니다.\n\n■ 기간: 9월 ~ 12월 (4개월)\n■ 지원 자격: 2학년 이상 재학생\n■ 지원금: 월 80만원\n■ 학점: 최대 6학점 인정" },
  { id: 20, category: "학사", title: "2학기 등록금 분할 납부 신청 안내", author: "송예린", department: "재무회계팀", createdAt: "2026-08-03", dueDate: "2026-08-25", views: 523, isPinned: false,
    content: "등록금 분할 납부를 원하는 학생은 기간 내에 신청해 주세요.\n\n■ 분할 횟수: 최대 4회\n■ 신청 기간: 8월 10일 ~ 8월 25일\n■ 신청 방법: 학사정보시스템 > 등록 > 분할납부 신청" },
  { id: 19, category: "일반", title: "여름철 냉방기 운영 시간 조정", author: "최우진", department: "시설관리팀", createdAt: "2026-08-01", dueDate: null, views: 41, isPinned: false,
    content: "에너지 절약을 위해 냉방기 운영 시간을 조정합니다.\n\n■ 운영 시간: 09:00 ~ 18:00\n■ 적용 기간: 8월 1일 ~ 8월 31일" },
  { id: 18, category: "학사", title: "졸업 예정자 학점 확인 요청", author: "박서연", department: "학사지원팀", createdAt: "2026-07-30", dueDate: "2026-08-29", views: 289, isPinned: false,
    content: "2027년 2월 졸업 예정자는 졸업 요건 충족 여부를 반드시 확인해 주세요.\n\n■ 확인 방법: 학사정보시스템 > 졸업 > 졸업사정 조회\n■ 미충족 시 2학기 수강신청에 반영해야 합니다." },
  { id: 17, category: "장학", title: "저소득층 생활지원 장학금 신청", author: "김민준", department: "학생지원팀", createdAt: "2026-07-29", dueDate: "2026-08-22", views: 176, isPinned: false,
    content: "경제적 어려움을 겪는 재학생을 지원합니다.\n\n■ 대상: 소득분위 4분위 이하\n■ 지급액: 학기당 100만원\n■ 제출 서류: 신청서, 가족관계증명서, 소득 증빙" },
  { id: 16, category: "행사", title: "신입생 학과별 오리엔테이션 일정", author: "이도현", department: "총학생회", createdAt: "2026-07-28", dueDate: null, views: 118, isPinned: false,
    content: "2학기 편입생과 신입생을 위한 오리엔테이션 일정입니다.\n\n■ 일시: 8월 28일(금) 14:00\n■ 장소: 학과별 강의실 (학과 공지 확인)" },
  { id: 15, category: "채용", title: "공무원 시험 대비 스터디 그룹 모집", author: "정하윤", department: "취업지원센터", createdAt: "2026-07-27", dueDate: "2026-08-12", views: 154, isPinned: false,
    content: "9급 공무원 시험을 준비하는 재학생 스터디를 운영합니다.\n\n■ 모집 인원: 15명\n■ 운영 기간: 9월 ~ 12월\n■ 지원: 교재비 및 스터디룸 제공" },
  { id: 14, category: "학사", title: "재학생 전공 변경 신청 안내", author: "박서연", department: "학사지원팀", createdAt: "2026-07-25", dueDate: "2026-08-14", views: 203, isPinned: false,
    content: "전공 변경을 희망하는 재학생의 신청을 받습니다.\n\n■ 신청 자격: 2학기 이상 이수, 평점 2.5 이상\n■ 선발 방법: 서류 및 면접\n■ 신청 기간: 8월 3일 ~ 8월 14일" },
  { id: 13, category: "일반", title: "도서관 하계 휴관일 안내", author: "윤서아", department: "학술정보원", createdAt: "2026-07-24", dueDate: null, views: 87, isPinned: false,
    content: "시설 점검을 위해 도서관을 휴관합니다.\n\n■ 휴관일: 8월 14일(금)\n■ 전자 자료는 정상 이용 가능합니다." },
  { id: 12, category: "장학", title: "해외 연수 장학 프로그램 설명회", author: "김민준", department: "국제교류팀", createdAt: "2026-07-22", dueDate: "2026-08-13", views: 132, isPinned: false,
    content: "겨울 방학 해외 어학연수 장학 프로그램을 소개합니다.\n\n■ 설명회: 8월 13일(목) 15:00, 본관 2층 세미나실\n■ 대상 국가: 일본, 대만, 싱가포르\n■ 지원 내용: 항공료 및 등록금 일부" },
  { id: 11, category: "행사", title: "학과별 전공 경진대회 개최", author: "한지우", department: "산학협력단", createdAt: "2026-07-21", dueDate: "2026-09-10", views: 76, isPinned: false,
    content: "전공 역량을 겨루는 교내 경진대회를 개최합니다.\n\n■ 접수: 8월 20일 ~ 9월 10일\n■ 본선: 10월 8일\n■ 시상: 대상 200만원 외 다수" },
  { id: 10, category: "채용", title: "취업 특강 - 포트폴리오 만들기", author: "정하윤", department: "취업지원센터", createdAt: "2026-07-20", dueDate: null, views: 245, isPinned: false,
    content: "실무자가 직접 알려주는 포트폴리오 제작 특강입니다.\n\n■ 일시: 8월 20일(목) 14:00\n■ 대상: 전 학년\n■ 장소: 창의관 401호" },
  { id: 9, category: "학사", title: "휴학 및 복학 신청 기간 안내", author: "박서연", department: "학사지원팀", createdAt: "2026-07-18", dueDate: "2026-08-28", views: 312, isPinned: false,
    content: "2학기 휴학과 복학 신청 기간입니다.\n\n■ 기간: 8월 1일 ~ 8월 28일\n■ 방법: 학사정보시스템에서 신청 후 학과 승인" },
  { id: 8, category: "일반", title: "교내 무선 네트워크 개선 작업", author: "최우진", department: "정보전산원", createdAt: "2026-07-17", dueDate: null, views: 58, isPinned: false,
    content: "무선 네트워크 장비 교체 작업을 진행합니다.\n\n■ 작업일: 8월 18일 ~ 8월 19일\n■ 영향: 작업 시간 중 일시적 접속 불가" },
  { id: 7, category: "장학", title: "봉사활동 우수자 장학금 추천 요청", author: "김민준", department: "학생지원팀", createdAt: "2026-07-15", dueDate: "2026-08-20", views: 94, isPinned: false,
    content: "봉사 시간이 우수한 학생을 학과별로 추천해 주세요.\n\n■ 추천 기준: 연간 봉사 40시간 이상\n■ 마감: 8월 20일" },
  { id: 6, category: "행사", title: "총장배 e스포츠 대회 참가팀 모집", author: "이도현", department: "총학생회", createdAt: "2026-07-14", dueDate: "2026-08-30", views: 167, isPinned: false,
    content: "총장배 e스포츠 대회를 개최합니다.\n\n■ 종목: LOL, 배틀그라운드\n■ 접수: 8월 30일까지\n■ 상금: 종목별 100만원" },
  { id: 5, category: "채용", title: "직무 적성 검사 무료 응시 안내", author: "정하윤", department: "취업지원센터", createdAt: "2026-07-12", dueDate: "2026-08-31", views: 138, isPinned: false,
    content: "재학생 대상 직무 적성 검사를 무료로 제공합니다.\n\n■ 신청: 취업지원센터 방문 또는 온라인\n■ 결과 상담도 함께 제공됩니다." },
  { id: 4, category: "학사", title: "교직 과정 이수 신청 안내", author: "박서연", department: "학사지원팀", createdAt: "2026-07-10", dueDate: "2026-08-18", views: 109, isPinned: false,
    content: "교직 과정 이수를 희망하는 학생의 신청을 받습니다.\n\n■ 자격: 1학년 성적 상위 30% 이내\n■ 신청 기간: 8월 3일 ~ 8월 18일" },
  { id: 3, category: "일반", title: "기숙사 2학기 입사 신청 안내", author: "윤서아", department: "생활관운영팀", createdAt: "2026-07-08", dueDate: "2026-08-15", views: 421, isPinned: false,
    content: "생활관 2학기 입사 신청을 받습니다.\n\n■ 신청 기간: 8월 1일 ~ 8월 15일\n■ 선발 기준: 통학 거리, 소득분위, 직전 학기 성적\n■ 입사일: 8월 30일(일)\n\n합격자는 8월 20일 생활관 홈페이지에 발표됩니다." },
  { id: 2, category: "일반", title: "기숙사 생활 수칙 개정 안내", author: "윤서아", department: "생활관운영팀", createdAt: "2026-07-05", dueDate: null, views: 73, isPinned: false,
    content: "2학기부터 적용되는 생활관 수칙 변경 사항입니다.\n\n■ 점호 시간 조정: 23:00 → 24:00\n■ 취사 구역 확대\n■ 자세한 내용은 생활관 홈페이지를 확인하세요." },
  { id: 1, category: "학사", title: "2026학년도 2학기 학사일정 확정", author: "박서연", department: "학사지원팀", createdAt: "2026-07-01", dueDate: null, views: 634, isPinned: false,
    content: "2학기 주요 학사일정을 안내합니다.\n\n■ 개강: 9월 1일(화)\n■ 중간고사: 10월 20일 ~ 10월 24일\n■ 기말고사: 12월 15일 ~ 12월 19일\n■ 종강: 12월 19일(금)" },
];

/* 학교 안내 문서 — SC-07 이 이 데이터를 읽어 화면 하나로 전부 처리합니다 */
window.PAGES = [
  { slug: "greeting", menu: "대학안내", title: "총장 인사말",
    body: "한빛공업전문대학 홈페이지를 찾아주신 여러분을 환영합니다.\n\n우리 대학은 1958년 개교 이래 실무 중심 교육으로 산업 현장이 필요로 하는 인재를 길러왔습니다. 이론에 머무르지 않고 직접 만들고 실험하며 배우는 것, 그것이 우리가 지켜온 방식입니다.\n\n젊음의 앞이 늘 당당할 수 있도록 함께 걷겠습니다." },
  { slug: "history", menu: "대학안내", title: "대학 연혁",
    body: "1958년  한빛공업고등기술학교 설립 인가\n1972년  한빛공업전문학교로 개편\n1998년  한빛공업전문대학으로 교명 변경\n2012년  창의관 준공, 산학협력단 출범\n2020년  LINC 사업 선정\n2026년  개교 68주년" },
  { slug: "campus", menu: "대학안내", title: "캠퍼스 안내",
    body: "본관   행정실, 대강의실, 학생지원팀\n창의관  실습실, 컴퓨터실, 스튜디오\n학술정보원  도서관, 열람실, 그룹 스터디룸\n생활관  기숙사 A동 · B동\n체육관  실내 체육관, 헬스장" },
  { slug: "location", menu: "대학안내", title: "오시는 길",
    body: "주소: 인천광역시 미추홀구 한빛로 100\n\n지하철: 1호선 도원역 2번 출구에서 도보 12분\n버스: 8, 15, 24, 519번 한빛대학 정류장 하차\n주차: 제1주차장 이용 (제2주차장은 8월 28일까지 공사)" },

  { slug: "departments", menu: "학과안내", title: "학과 목록",
    body: "컴퓨터정보공학과\n기계공학과\n전기전자공학과\n건축인테리어과\n경영정보과\n시각디자인과" },
  { slug: "dept-cs", menu: "학과안내", title: "컴퓨터정보공학과",
    body: "소프트웨어 개발과 정보 시스템 운영 능력을 갖춘 실무 인재를 기릅니다.\n\n주요 교과목\n- 프로그래밍 기초 / 자료구조\n- 웹 프론트엔드 / 백엔드 개발\n- 데이터베이스 / 네트워크\n- 캡스톤 디자인\n\n졸업 후 진로: 웹 개발자, 시스템 엔지니어, 데이터 분석가" },
  { slug: "dept-me", menu: "학과안내", title: "기계공학과",
    body: "설계부터 가공까지 전 과정을 다루는 기계 전문 인력을 양성합니다.\n\n주요 교과목\n- 기계 제도 / CAD\n- 재료역학 / 유체역학\n- CNC 가공 실습\n- 자동화 시스템" },

  { slug: "admission-susi", menu: "입학안내", title: "수시 모집",
    body: "원서 접수: 9월 9일 ~ 9월 12일\n서류 마감: 9월 15일\n합격 발표: 11월 1일\n\n전형 방법: 학생부 교과 100%" },
  { slug: "admission-jeongsi", menu: "입학안내", title: "정시 모집",
    body: "원서 접수: 12월 29일 ~ 1월 2일\n합격 발표: 1월 20일\n\n전형 방법: 수능 100% 또는 학생부 100% 중 선택" },
  { slug: "admission-scholarship", menu: "입학안내", title: "신입생 장학 혜택",
    body: "성적우수 장학: 등록금 전액 ~ 50%\n지역인재 장학: 등록금 30%\n특기자 장학: 등록금 30% ~ 50%\n\n중복 수혜는 불가하며 가장 유리한 항목이 자동 적용됩니다." },

  { slug: "calendar", menu: "학사안내", title: "학사 일정 안내",
    body: "9월 1일    2학기 개강\n9월 19일   수강 정정 마감\n10월 20일  중간고사 시작\n11월 10일  기말 수강 취소 마감\n12월 15일  기말고사 시작\n12월 19일  종강" },
  { slug: "course", menu: "학사안내", title: "수강 신청 안내",
    body: "수강 신청은 학사정보시스템에서 진행합니다.\n\n1. 학사정보시스템 로그인\n2. 수강신청 > 개설 강좌 조회\n3. 장바구니 담기 후 신청\n\n학기당 최대 21학점까지 신청할 수 있습니다." },
  { slug: "graduation", menu: "학사안내", title: "졸업 요건",
    body: "총 이수 학점: 80학점 이상\n전공 필수: 45학점 이상\n교양 필수: 15학점 이상\n\n졸업 인증: 전공 자격증 1개 이상 또는 캡스톤 디자인 이수" },

  { slug: "scholarship", menu: "대학생활", title: "장학제도 안내",
    body: "교내 장학\n- 성적우수 장학 / 근로 장학 / 봉사 장학 / 생활지원 장학\n\n교외 장학\n- 국가장학금 Ⅰ·Ⅱ 유형 / 국가근로장학금 / 지자체 장학\n\n자세한 신청 방법은 공지사항의 장학 카테고리를 확인하세요." },
  { slug: "dorm", menu: "대학생활", title: "기숙사 안내",
    body: "생활관 A동  남학생 2인실 · 4인실\n생활관 B동  여학생 2인실 · 4인실\n\n비용: 학기당 95만원 (식비 별도)\n선발 기준: 통학 거리, 소득분위, 직전 학기 성적" },
  { slug: "club", menu: "대학생활", title: "동아리 안내",
    body: "학술  프로그래밍, 로보틱스, 창업\n체육  축구, 농구, 클라이밍\n문화  밴드, 사진, 연극\n봉사  지역 아동센터 교육 봉사\n\n가입 문의는 총학생회로 연락하세요." },

  { slug: "forms", menu: "정보광장", title: "학사 서식",
    body: "휴학 신청서\n복학 신청서\n전공 변경 신청서\n성적 정정 요청서\n증명서 발급 신청서\n\n서식은 학사지원팀에서 내려받을 수 있습니다." },
  { slug: "faq", menu: "정보광장", title: "자주 묻는 질문",
    body: "Q. 증명서는 어디서 발급받나요?\nA. 본관 1층 무인 발급기 또는 학사정보시스템에서 온라인 발급이 가능합니다.\n\nQ. 수강 정정은 몇 번까지 가능한가요?\nA. 정정 기간 중에는 횟수 제한 없이 가능합니다.\n\nQ. 장학금 신청 결과는 언제 나오나요?\nA. 신청 마감 후 약 3주 뒤 학사정보시스템에서 확인할 수 있습니다." },
];

window.GNB = [
  { menu: "대학안내", slug: "greeting" },
  { menu: "학과안내", slug: "departments" },
  { menu: "입학안내", slug: "admission-susi" },
  { menu: "학사안내", slug: "calendar" },
  { menu: "대학생활", slug: "scholarship" },
  { menu: "정보광장", slug: null },
];
